package com.limechain.limeapi.http.response;

import lombok.*;

import java.util.List;

@Getter
@Setter
@EqualsAndHashCode
public class TransactionsDTO {

    private List<Transaction> transactions;

    @Data
    @Builder
    public static class Transaction {
        private String transactionHash; // Hex encoded transaction hash
        private int transactionStatus;  // Status of the transaction (1 for success, 0 for failure)
        private String blockHash;       // Hex encoding of the block hash
        private String blockNumber;       // Block number
        private String from;            // Ethereum address of the sender
        private String to;              // Ethereum address of the receiver (nullable)
        private String contractAddress; // Ethereum address of the created contract (nullable)
        private int logsCount;          // Number of logs generated by the transaction
        private String input;           // Hex encoded data sent along with the transaction
        private String value;           // Value transferred in wei
    }
}

