server:
  port: ${API_PORT}
spring:
  application:
    name: etherium
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.xml
    url: ${DB_CONNECTION_URL}
    driver-class-name: org.postgresql.Driver
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
